config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get '/tasks', to: 'tasks#index'
  get '/tasks/:id', to: 'tasks#show', as: 'task'
  get '/tasks/new', to: 'tasks#new', as: 'new_task'
  post '/tasks', to: 'tasks#create'




  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end
def show
  @task = Task.find(params[:id])

end

def new
  @task = Task.new
end

def create
  @task = Task.new(task_params)

  if @task.save
    redirect_to tasks_path
  else
    render 'new'
  end
end

private

def task_params
  params.require(:task).permit(:title, :details, :completed)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<ul>
  <% @tasks.each do |task| %>
    <li>
      <%= link_to task.title, task_path(task) %>
    </li>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<!-- app/views/tasks/new.html.erb -->
<h1>New Task</h1>

<%= form_with(model: @task, url: tasks_path, method: :post) do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %><br>

  <%= form.label :details %>
  <%= form.text_area :details %><br>

  <%= form.label :completed %>
  <%= form.check_box :completed %><br>

  <%= form.submit %>
<% end %>